/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gaji.view;

import gaji.controller.ControllerGaji;
import gaji.controller.ControllerKaryawan;
import gaji.controller.ControllerPotongan;
import gaji.controller.ControllerReport;
import gaji.controller.ControllerTransaksi;
import java.util.List;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Gaji;
import model.Karyawan;
import model.Potongan;
import model.Transaksi;

/**
 *
 * @author User
 */
public class SlipGaji extends javax.swing.JFrame {
    ControllerKaryawan controllerKaryawan = new ControllerKaryawan(); 
    ControllerTransaksi controllertransaksi = new ControllerTransaksi();
    ControllerGaji controllergaji = new ControllerGaji();
    ControllerPotongan Controllerpotongan = new ControllerPotongan();
    ControllerReport controllerrepport = new ControllerReport();
    /**
     * Creates new form SlipGaji
     */
    public SlipGaji() {
        initComponents();
        calendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchdata = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgaji = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblpotongan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lblurut = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblgaji = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbljabatan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblkedisiplinan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblttransport = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblprestasi = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblpphgaji = new javax.swing.JLabel();
        lblalaingaji = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbllainpot = new javax.swing.JLabel();
        lblpphpot = new javax.swing.JLabel();
        lblbpjs2 = new javax.swing.JLabel();
        lblterlambat = new javax.swing.JLabel();
        lblalfa = new javax.swing.JLabel();
        lblizin = new javax.swing.JLabel();
        lblbpjs = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblgapok = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        lblgajibersih = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblbpjsgaji = new javax.swing.JLabel();
        lblbpjs2gaji = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lbltotalgaji = new javax.swing.JLabel();
        lbltotalpot = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        jLabel21.setText("Nama");

        txtPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarianActionPerformed(evt);
            }
        });
        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");

        jLabel22.setText("Hasil Pencarian");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblResult);

        javax.swing.GroupLayout searchdataLayout = new javax.swing.GroupLayout(searchdata.getContentPane());
        searchdata.getContentPane().setLayout(searchdataLayout);
        searchdataLayout.setHorizontalGroup(
            searchdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(txtPencarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(searchdataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        searchdataLayout.setVerticalGroup(
            searchdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchdataLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(searchdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblgaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblgaji);

        tblpotongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblpotongan);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton13.setText("Search Karyawan");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nama :");

        jLabel2.setText("ID : ");

        lblnama.setText(" a");

        lblurut.setText("0");

        lbltgl.setText("0");

        jLabel6.setText("Gaji : ");

        lblgaji.setText("0");

        jLabel8.setText("Gaji Pokok :");

        jLabel9.setText("RP. ");

        jLabel10.setText("Tunj. Jabatan :");

        lbljabatan.setText("0");

        jLabel12.setText("Tunj. Kedisiplimam :");

        lblkedisiplinan.setText("0");

        jLabel14.setText("Transport :");

        lblttransport.setText("0");

        jLabel16.setText("Tunj. Prestasi : ");

        lblprestasi.setText("0");

        jLabel18.setText("Tunj. PPH 21 : ");

        jLabel19.setText("Lain - Lain : ");

        lblpphgaji.setText("0");

        lblalaingaji.setText("0");

        jLabel24.setText("Total Gaji Bersih : ");

        jLabel25.setText("Potongan :");

        jLabel26.setText("Izin : ");

        jLabel27.setText("Alfa : ");

        jLabel28.setText("Terlambat : ");

        jLabel29.setText("BPJS Kesehatan : ");

        jLabel30.setText("BPJS Ketenagakerjaan : ");

        lbllainpot.setText("0");

        lblpphpot.setText("0");

        lblbpjs2.setText("0");

        lblterlambat.setText("0");

        lblalfa.setText("0");

        lblizin.setText("0");

        lblbpjs.setText("0");

        jLabel38.setText("PPH : ");

        jLabel39.setText("Lain - Lain : ");

        jLabel40.setText("RP. ");

        lblgapok.setText("0");

        jLabel41.setText("RP. ");

        jLabel42.setText("RP. ");

        jLabel43.setText("RP. ");

        jLabel44.setText("RP. ");

        jLabel45.setText("RP. ");

        jLabel46.setText("RP. ");

        jLabel47.setText("RP. ");

        jLabel48.setText("RP. ");

        jLabel49.setText("RP. ");

        jLabel50.setText("RP. ");

        jLabel51.setText("RP. ");

        jLabel52.setText("RP. ");

        jLabel11.setText("RP. ");

        jLabel53.setText("RP. ");

        lblgajibersih.setText("0");

        jLabel3.setText("Periode ");

        jLabel4.setText("BPJS Kesehatan : ");

        jLabel5.setText("BPJS Ketenagakerjaan : ");

        lblbpjsgaji.setText("0");

        lblbpjs2gaji.setText("0");

        jLabel54.setText("RP. ");

        jLabel55.setText("RP. ");

        jLabel7.setText("TOTAL : ");

        jLabel13.setText("TOTAL : ");

        jLabel56.setText("RP. ");

        jLabel57.setText("RP. ");

        lbltotalgaji.setText("0");

        lbltotalpot.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblnama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblurut))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(50, 50, 50))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel16)
                                .addComponent(jLabel18)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel53)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblgajibersih))
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel19)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel46)
                                                .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel43)
                                                .addComponent(jLabel41)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblbpjsgaji)
                                        .addComponent(lblkedisiplinan)
                                        .addComponent(lbljabatan)
                                        .addComponent(lblpphgaji)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblttransport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblprestasi, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(lblgapok)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel54)
                                        .addComponent(jLabel56))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblalaingaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblbpjs2gaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbltotalgaji)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel40)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltgl))
                    .addComponent(jLabel25)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel57))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel47)
                                        .addComponent(jLabel49)
                                        .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel50)
                                        .addComponent(jLabel52)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblpphpot)
                            .addComponent(lbllainpot)
                            .addComponent(lblterlambat)
                            .addComponent(lblbpjs)
                            .addComponent(lblbpjs2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblizin)
                                .addComponent(lblalfa))
                            .addComponent(lbltotalpot))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblurut))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblgaji)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblgapok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbljabatan)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblkedisiplinan)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblttransport)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblprestasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblpphgaji)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblbpjsgaji)
                                    .addComponent(jLabel55))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbpjs2gaji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblalaingaji)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltotalgaji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel53)
                            .addComponent(lblgajibersih)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltgl)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel52)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel51)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel48)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel47))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblizin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblalfa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblterlambat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblbpjs)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblbpjs2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblpphpot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbllainpot)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel39)))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel57)
                    .addComponent(lbltotalpot))
                .addGap(85, 85, 85))
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        setTableKaryawan(controllerKaryawan.getAllData());
        searchdata.setVisible(true);
        searchdata.requestFocusInWindow();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarianActionPerformed

    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped

    }//GEN-LAST:event_txtPencarianKeyTyped

    private void tblResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMousePressed
        if(evt.getClickCount() == 2){
            String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
            int idxrow = tblResult.getSelectedRow();
            if(colName.equals("Id Urutan")){
                lblurut.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblnama.setText(tblResult.getModel().getValueAt(idxrow, 1).toString());
                
                setTablePotongan(Controllerpotongan.getDataById(Integer.parseInt(tblResult.getModel().getValueAt(idxrow, 0).toString())));
                setTableGaji(controllergaji.getGajibyId(Integer.parseInt(tblResult.getModel().getValueAt(idxrow, 0).toString())));
            
                searchdata.dispose();
                this.setVisible(true);
                }
                lblalfa.setText(tblpotongan.getModel().getValueAt(0, 1).toString());
                lblizin.setText(tblpotongan.getModel().getValueAt(0, 2).toString());
                lblterlambat.setText(tblpotongan.getModel().getValueAt(0, 3).toString());
                lblbpjs.setText(tblpotongan.getModel().getValueAt(0, 4).toString());
                lblbpjs2.setText(tblpotongan.getModel().getValueAt(0, 5).toString());
                lblpphpot.setText(tblpotongan.getModel().getValueAt(0, 6).toString());
                lbllainpot.setText(tblpotongan.getModel().getValueAt(0, 7).toString());
                
                lblgaji.setText(tblgaji.getModel().getValueAt(0, 1).toString());
                lblgapok.setText(tblgaji.getModel().getValueAt(0, 2).toString());
                lbljabatan.setText(tblgaji.getModel().getValueAt(0, 3).toString());
                lblkedisiplinan.setText(tblgaji.getModel().getValueAt(0, 4).toString());
                lblttransport.setText(tblgaji.getModel().getValueAt(0, 5).toString());
                lblprestasi.setText(tblgaji.getModel().getValueAt(0, 6).toString());
                lblpphgaji.setText(tblgaji.getModel().getValueAt(0, 7).toString());
                lblbpjsgaji.setText(tblgaji.getModel().getValueAt(0, 8).toString());
                lblbpjs2gaji.setText(tblgaji.getModel().getValueAt(0, 9).toString());
                lblalaingaji.setText(tblgaji.getModel().getValueAt(0, 10).toString());
                
                Double alfa = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 1).toString());
                Double izin = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 2).toString());
                Double terlambat = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 3).toString());
                Double bpjs1 = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 4).toString());
                Double bpjs2 = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 5).toString());
                Double pphpot = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 6).toString());
                Double lainpot = Double.parseDouble(tblpotongan.getModel().getValueAt(0, 7).toString());
                
                Double totalpotongan = alfa+izin+terlambat+bpjs1+bpjs2+pphpot+lainpot;
                lbltotalpot.setText(String.valueOf(totalpotongan));
                
                Double gaji = Double.parseDouble(tblgaji.getModel().getValueAt(0, 1).toString());
                Double gapok = Double.parseDouble(tblgaji.getModel().getValueAt(0, 2).toString());
                Double jabatan = Double.parseDouble(tblgaji.getModel().getValueAt(0, 3).toString());
                Double kedisiplinan = Double.parseDouble(tblgaji.getModel().getValueAt(0, 4).toString());
                Double transport = Double.parseDouble(tblgaji.getModel().getValueAt(0, 5).toString());
                Double prestasi = Double.parseDouble(tblgaji.getModel().getValueAt(0, 6).toString());
                Double pphgaji = Double.parseDouble(tblgaji.getModel().getValueAt(0, 7).toString());
                Double bpjs1gaji = Double.parseDouble(tblgaji.getModel().getValueAt(0, 8).toString());
                Double bpjs2gaji = Double.parseDouble(tblgaji.getModel().getValueAt(0, 9).toString());
                Double laingaji = Double.parseDouble(tblgaji.getModel().getValueAt(0, 10).toString());
                
                Double totalgaji = gaji+gapok+jabatan+kedisiplinan+transport+prestasi+pphgaji+bpjs1gaji+bpjs2gaji+laingaji;
                lbltotalgaji.setText(String.valueOf(totalgaji));
                
                lblgajibersih.setText(String.valueOf(totalgaji-totalpotongan));
        }
    }//GEN-LAST:event_tblResultMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int id = Integer.parseInt(lblurut.getText());
        String nama = lblnama.getText();
        double totalgaji = Double.parseDouble(lbltotalgaji.getText());
        double totalpotongan = Double.parseDouble(lbltotalpot.getText());
        double gajibersih = Double.parseDouble(lblgajibersih.getText());
        
        if(btnSimpan.getText().equals("Save")){
            if(controllerrepport.insertReport(id, nama,totalgaji,totalpotongan,gajibersih)){
                
            } 
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    private void calendar(){
        String[] monthname = {"Januari","Februari","Maret","APril","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"};
        Calendar now = Calendar.getInstance();
        
        lbltgl.setText(monthname[now.get(Calendar.MONTH)]);
    }
    private void setTableGaji(List <Gaji> listGaji){
        if(listGaji==null){
            JOptionPane.showMessageDialog(this, "Data " + "Gaji gagal diambil dari database","Database Failed",JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
            new String[]{
                "Nama",
                "Gaji",
                "Gaji Pokok",
                "Jabatan",
                "Kedisiplinan",
                "Transport",
                "Prestasi",
                "PPh 21",
                "Bpjs Kesehatan",
                "Bpjs Ketenagakerjaan",
                "Lain-lain"
            }
            );
            for (Gaji g : listGaji){    
                Object[] o = new Object[11];
                o[0] = g.getNama_karyawan();
                o[1] = g.getGaji();
                o[2] = g.getGaji_Pokok();
                o[3] = g.getTunjangan_Jabatan();
                o[4] = g.getTunjangan_Kedisiplinan();
                o[5] = g.getTransport();
                o[6] = g.getTunjangan_prestasi();
                o[7] = g.getTunjangan_pph();
                o[8] = g.getBpjs_kesehatan();
                o[9] = g.getBpjs_ketenagakerjaan();
                o[10] = g.getLain_lain();
                tableModel.addRow(o);
            }
            tblgaji.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblgaji.setModel(tableModel);
        }
    }
   
    private void setTableKaryawan(List <Karyawan> listKaryawan){
        if (listKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Urutan",
                   "Nama Karyawan"
               }
           );
           for (Karyawan p : listKaryawan) {
               Object[] o = new Object[2];
               o[0] = p.getId_urutan();
               o[1] = p.getNama_karyawan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    private void setTablePotongan(List <Potongan> listTransaksi){
        if (listTransaksi==null){
           JOptionPane.showMessageDialog(this, "Data gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Urutan",
                   "Alfa",
                   "Izin",
                   "Terlambat",
                   "Bpjs Kesehatan",
                   "Bpjs Ketenagakerjaan",
                   "PPh 21",
                   "Lain-lain"
               }
           );
           for (Potongan p : listTransaksi) {
               Object[] o = new Object[8];
               o[0] = p.getId_urutan();
               o[1] = p.getAlfa();
               o[2] = p.getIzin();
               o[3] = p.getTerlambat();
               o[4] = p.getKesehatan();
               o[5] = p.getKetenagakerjaan();
               o[6] = p.getPph();
               o[7] = p.getLain();
               tableModel.addRow(o);
           }
           tblpotongan.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblpotongan.setModel(tableModel);
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlipGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlipGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlipGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlipGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlipGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblalaingaji;
    private javax.swing.JLabel lblalfa;
    private javax.swing.JLabel lblbpjs;
    private javax.swing.JLabel lblbpjs2;
    private javax.swing.JLabel lblbpjs2gaji;
    private javax.swing.JLabel lblbpjsgaji;
    private javax.swing.JLabel lblgaji;
    private javax.swing.JLabel lblgajibersih;
    private javax.swing.JLabel lblgapok;
    private javax.swing.JLabel lblizin;
    private javax.swing.JLabel lbljabatan;
    private javax.swing.JLabel lblkedisiplinan;
    private javax.swing.JLabel lbllainpot;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblpphgaji;
    private javax.swing.JLabel lblpphpot;
    private javax.swing.JLabel lblprestasi;
    private javax.swing.JLabel lblterlambat;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JLabel lbltotalgaji;
    private javax.swing.JLabel lbltotalpot;
    private javax.swing.JLabel lblttransport;
    private javax.swing.JLabel lblurut;
    private javax.swing.JDialog searchdata;
    private javax.swing.JTable tblResult;
    private javax.swing.JTable tblgaji;
    private javax.swing.JTable tblpotongan;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
