/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gaji.view;

import gaji.controller.ControllerKaryawan;
import gaji.controller.ControllerTransaksi;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Karyawan;
import model.Transaksi;

/**
 *
 * @author A s u s
 */
public class TransaksiTambah extends javax.swing.JFrame {
    ControllerKaryawan controllerKaryawan = new ControllerKaryawan();
    ControllerTransaksi controllerTransaksi = new ControllerTransaksi();
    List<Transaksi> collection = new ArrayList<>();
    
    /**
     * Creates new form TransaksiTambah
     */
    public TransaksiTambah() {
        initComponents();
        initData();
        setTableTransaksi(controllerTransaksi.getAllData());
    }
    
    public void initData(){
        setTableTransaksi(controllerTransaksi.getAllData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchData = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        popup = new javax.swing.JPopupMenu();
        mnDelete = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        lblUrut = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxIzin = new javax.swing.JComboBox<>();
        cbxAlfa = new javax.swing.JComboBox<>();
        cbxTerlambat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtKesehatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKetenagakerjaan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPph = new javax.swing.JTextField();
        txtLain = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        outCommand = new javax.swing.JLabel();

        searchData.setMinimumSize(new java.awt.Dimension(416, 458));

        jLabel21.setText("Nama");

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");

        jLabel22.setText("Hasil Pencarian");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblResult);

        javax.swing.GroupLayout searchDataLayout = new javax.swing.GroupLayout(searchData.getContentPane());
        searchData.getContentPane().setLayout(searchDataLayout);
        searchDataLayout.setHorizontalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(txtPencarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(searchDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        searchDataLayout.setVerticalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        mnDelete.setText("Delete");
        mnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteActionPerformed(evt);
            }
        });
        popup.add(mnDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jButton13.setText("Search Karyawan");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        lblUrut.setText("No Urut");

        lblNama.setText("Nama Karyawan");

        jLabel3.setText("Jumlah Izin");

        jLabel4.setText("JumlahAlfa");

        jLabel5.setText("Jumlah Terlambat");

        cbxIzin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbxAlfa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbxTerlambat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel6.setText("BPJS Kesehatan");

        txtKesehatan.setText("Rp.000,00-");

        jLabel7.setText("BPJS Ketenagakerjaan");

        txtKetenagakerjaan.setText("Rp.000,00-");

        jLabel8.setText("PPh 21");

        txtPph.setText("Rp.000,00-");
        txtPph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPphActionPerformed(evt);
            }
        });

        txtLain.setText("Rp.000,00-");

        jLabel9.setText("Lain - lain");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblUrut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNama))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxIzin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxAlfa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKesehatan)
                                    .addComponent(cbxTerlambat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKetenagakerjaan)
                                    .addComponent(txtPph)
                                    .addComponent(txtLain, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(lblUrut)
                    .addComponent(lblNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbxAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKesehatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKetenagakerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Input Potongan Gaji");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Proses");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        btnClose.setText("Close");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Output");

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Alfa", "Izin", "Terlambat", "BPJS kesehatan", "BPJS Ketenagakerjaan", "PPh 21", "Lain - lain"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTransaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        outCommand.setText("Ready");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(202, 202, 202)
                                .addComponent(outCommand))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(outCommand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped
        
    }//GEN-LAST:event_txtPencarianKeyTyped

    private void tblResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMousePressed
        if(evt.getClickCount() == 2){
            String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
            int idxrow = tblResult.getSelectedRow();
            if(colName.equals("Id Urutan")){
                lblUrut.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblNama.setText(tblResult.getModel().getValueAt(idxrow, 1).toString());
            }
            searchData.dispose();
            setTableTransaksi(controllerTransaksi.getAllData());
            this.setVisible(true);
        }

    }//GEN-LAST:event_tblResultMousePressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        setTableKaryawan(controllerKaryawan.getAllData());
        searchData.setVisible(true);
        searchData.requestFocusInWindow();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int id_urutan = Integer.parseInt(lblUrut.getText());
        double izin = Double.parseDouble(cbxIzin.getSelectedItem().toString());
        double alfa = Double.parseDouble(cbxAlfa.getSelectedItem().toString());
        double terlambat = Double.parseDouble(cbxTerlambat.getSelectedItem().toString());
        double kesehatan = Double.parseDouble(txtKesehatan.getText());
        double ketenagakerjaan = Double.parseDouble(txtKetenagakerjaan.getText());
        double pph = Double.parseDouble(txtPph.getText());
        double lain = Double.parseDouble(txtLain.getText());
        
        if(btnSimpan.getText().equals("Simpan")){
            if(controllerTransaksi.insertTransaksi(id_urutan, izin, alfa, terlambat, kesehatan, ketenagakerjaan, pph, lain)){
                setTableTransaksi(controllerTransaksi.getAllData());
                outCommand.setText("Insert Berhasil");
            } else {
                outCommand.setText("Insert Gagal");
            }
        } else {
            if(controllerTransaksi.updateTransaksi(id_urutan, izin, alfa, terlambat, kesehatan, ketenagakerjaan, pph, lain)){
                setTableTransaksi(controllerTransaksi.getAllData());
                outCommand.setText("Update Berhasil");
            } else {
                outCommand.setText("Update Gagal");
            }
        }
        setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMousePressed
       if(evt.getClickCount()==2){
           int idxrow = tblTransaksi.getSelectedRow();
           lblUrut.setText(tblTransaksi.getModel().getValueAt(idxrow, 0).toString());
           cbxIzin.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 1).toString());
           cbxAlfa.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 2).toString());
           cbxTerlambat.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 3).toString());
           txtKesehatan.setText(tblTransaksi.getModel().getValueAt(idxrow, 4).toString());
           txtKetenagakerjaan.setText(tblTransaksi.getModel().getValueAt(idxrow, 5).toString());
           txtPph.setText(tblTransaksi.getModel().getValueAt(idxrow, 6).toString());
           txtLain  .setText(tblTransaksi.getModel().getValueAt(idxrow, 7).toString());
           btnSimpan.setText("Update");
       }
       if(evt.isPopupTrigger()){
           popup.show(tblTransaksi, evt.getX(), evt.getY());
       }
    }//GEN-LAST:event_tblTransaksiMousePressed

    private void tblTransaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseReleased
        if(evt.getClickCount()==2){
           int idxrow = tblTransaksi.getSelectedRow();
           lblUrut.setText(tblTransaksi.getModel().getValueAt(idxrow, 0).toString());
           cbxIzin.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 1).toString());
           cbxAlfa.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 2).toString());
           cbxTerlambat.setSelectedItem(tblTransaksi.getModel().getValueAt(idxrow, 3).toString());
           txtKesehatan.setText(tblTransaksi.getModel().getValueAt(idxrow, 4).toString());
           txtKetenagakerjaan.setText(tblTransaksi.getModel().getValueAt(idxrow, 5).toString());
           txtPph.setText(tblTransaksi.getModel().getValueAt(idxrow, 6).toString());
           txtLain  .setText(tblTransaksi.getModel().getValueAt(idxrow, 7).toString());
           btnSimpan.setText("Update");
       }
       if(evt.isPopupTrigger()){
           popup.show(tblTransaksi, evt.getX(), evt.getY());
       }
    }//GEN-LAST:event_tblTransaksiMouseReleased

    private void mnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, 
                "Apakah Yakin Untuk Didelete?",
                "Delete Dialog", JOptionPane.YES_NO_OPTION
                );
        if(result == JOptionPane.YES_OPTION){
            int id = Integer.parseInt(tblTransaksi.getModel().getValueAt(tblTransaksi.getSelectedRow(), 0).toString());
            controllerTransaksi.deleteTransaksi(id);
            setClear();
            setTableTransaksi(controllerTransaksi.getAllData());
        }
    }//GEN-LAST:event_mnDeleteActionPerformed

    private void txtPphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPphActionPerformed

    private void setTableKaryawan(List <Karyawan> listKaryawan){
        if (listKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Urutan",
                   "Nama Karyawan"
               }
           );
           for (Karyawan p : listKaryawan) {
               Object[] o = new Object[2];
               o[0] = p.getId_urutan();
               o[1] = p.getNama_karyawan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableTransaksi(List <Transaksi> listTransaksi){
        if (listTransaksi==null){
           JOptionPane.showMessageDialog(this, "Data gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Urutan",
                   "Alfa",
                   "Izin",
                   "Terlambat",
                   "Bpjs Kesehatan",
                   "Bpjs Ketenagakerjaan",
                   "PPh 21",
                   "Lain-lain"
               }
           );
           for (Transaksi p : listTransaksi) {
               Object[] o = new Object[8];
               o[0] = p.getId_urutan();
               o[1] = p.getAlfa();
               o[2] = p.getIzin();
               o[3] = p.getTerlambat();
               o[4] = p.getKesehatan();
               o[5] = p.getKetenagakerjaan();
               o[6] = p.getPph();
               o[7] = p.getLain();
               tableModel.addRow(o);
           }
           tblTransaksi.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblTransaksi.setModel(tableModel);
       }
    }
    
    private void setClear(){
        cbxIzin.setSelectedIndex(0);
        cbxAlfa.setSelectedIndex(0);
        cbxTerlambat.setSelectedIndex(0);
        txtKesehatan.setText("");
        txtKetenagakerjaan.setText("");
        txtPph.setText("");
        txtLain.setText("");
        outCommand.setText("Ready");
        lblUrut.setText("No Urut");
        lblNama.setText("Nama Karyawan");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiTambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxAlfa;
    private javax.swing.JComboBox<String> cbxIzin;
    private javax.swing.JComboBox<String> cbxTerlambat;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblUrut;
    private javax.swing.JMenuItem mnDelete;
    private javax.swing.JLabel outCommand;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JDialog searchData;
    private javax.swing.JTable tblResult;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtKesehatan;
    private javax.swing.JTextField txtKetenagakerjaan;
    private javax.swing.JTextField txtLain;
    private javax.swing.JTextField txtPencarian;
    private javax.swing.JTextField txtPph;
    // End of variables declaration//GEN-END:variables
}
